### ISSUE TITLE
Github actions can't find this action

### ISSUE THREAD

**Issue by harikesh409** [vimtor/action-zip#14]
Hi,
A few days back I was able to successfully run the action but when I run today Github is unable to find the action.

## Error Message:
Unable to resolve action `papeloto/action-zip@v1`, unable to find version `v1`

**Comment by rico-ocepek** [comment]
Same here, our deployment pipelines currently fail due to this

**Comment by radugroza** [comment]
same here

**Comment by b0bben** [comment]
@radugroza @rico-ocepek I think it's because the repo changed owner/name to `vimtor`
Check pull request #13

**Comment by xeontem** [comment]
Surprise. It is breaking changes. Hope it will never happens again.

**Comment by piiertho** [comment]
This is happening because someone clever decided to create an organization named `papeloto` and call this a hack...  
See [here](https://github.com/papeloto/action-zip/issues/1).

**Comment by Oleksii14** [comment]
Guys, just use `vimtor/action-zip@1`
