### ISSUE TITLE
Update to Node JS 16

### ISSUE THREAD

**Issue by RobPasMue** [vimtor/action-zip#19]
We are using this action in several repositories and the GitHub workflows are currently throwing this warning:

```bash
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
Please update the following actions to use Node.js 16: vimtor/action-zip
```

Would it be possible to update the action?

**Comment by RobPasMue** [comment]
Pinging repository owner for visibility @vimtor

**Comment by germa89** [comment]
+1

**Comment by jmspereira** [comment]
@vimtor for when a release of a V2 with node 16?

**Comment by RobPasMue** [comment]
Yes, @vimtor, as I mentioned here https://github.com/vimtor/action-zip/pull/20#issuecomment-1288446144, a release is needed to solve these issues in other repositories consuming this action. Please consider doing a new release.

**Comment by germa89** [comment]
> Yes, @vimtor, as I mentioned here [#20 (comment)](https://github.com/vimtor/action-zip/pull/20#issuecomment-1288446144), a release is needed to solve these issues in other repositories consuming this action. Please consider doing a new release.

+1

**Comment by vimtor** [comment]
Done! Sorry for the delay

**Comment by RobPasMue** [comment]
> Done! Sorry for the delay

Thanks @vimtor!! Maybe also tag v1 to point to v1.1? Just a suggestion. Feel free to choose to do it or not
