### ISSUE TITLE
Node.js 12 actions are deprecated

### ISSUE THREAD

**Issue by patrickelectric** [vimtor/action-zip#24]
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: vimtor/action-zip@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

**Comment by hugoheml** [comment]
Hey,
You just need to upgrade the version that you use to `v1.1`

**Comment by willryan-stemcell** [comment]
Can you update https://github.com/vimtor/action-zip/blob/master/README.md with this info?

**Comment by hugoheml** [comment]
I'll do a PR

**Comment by NiklasEi** [comment]
Maybe the `v1` tag could be updated to point to the `v1.1` commit?

**Comment by willryan-stemcell** [comment]
Now Node 16 is deprecated:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: vimtor/action-zip@v1.1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by willryan-stemcell** [comment]
Can we get a new release (e.g. v1.2) from master so that we can point to the Node.js 20 change?

**Comment by vimtor** [comment]
@willryan-stemcell done!
