### ISSUE TITLE
Perhaps mention in the description that it only works on linux?

### ISSUE THREAD

**Issue by bofh69** [vimtor/action-zip#4]

**Comment by x3ro** [comment]
Not entirely sure where you get this from 🤔 I just built [a pipeline](https://github.com/next-slide-please/client/blob/e32d2096ea4d847cefe7de86430464f6703175da/.github/workflows/release.yml#L60) where I'm zipping files on `macos-latest`, `ubuntu-18.04` and `windows-latest` using this action and it's working fine.

**Comment by bofh69** [comment]
@x3ro It only worked on my linux target when I wrote this. Maybe macos-latest and windows-latest have been upgraded? Thanks for the report!

**Comment by x3ro** [comment]
Sounds plausible. As a tip for future created issues, it always helps maintainers and passerbys if you add _how_ something failed, i.e. error message or whatnot 🚀
