### ISSUE TITLE
Exclude Files from Zip

### ISSUE THREAD

**Issue by dcooney** [vimtor/action-zip#6]
👋🏻  This is working great, but I think it would be great to be able to exclude files from the zip versus explicitly including files using the `dest` command. 

Using a `distignore` for this would be perfect. Do you think this is possible?

**Comment by vimtor** [comment]
Yeah I think is possible! If you want to submit a PR I will happily merge it ❤️

**Comment by dcooney** [comment]
@vimtor I did fork the repo to do some testing. I believe it would require a complete refactor to recursively iterate over all files, directories and subdirectories. Probably doesn't make sense to PR to your action considering this.
